//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfix.Addin.IntelParallelStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProblemDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProblemDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cfix.Addin.IntelParallelStudio.ProblemDescriptions", typeof(ProblemDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect API call.
        /// </summary>
        internal static string pdr_call_invalid {
            get {
                return ResourceManager.GetString("pdr_call_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing allocation.
        /// </summary>
        internal static string pdr_dealloc_invalid {
            get {
                return ResourceManager.GetString("pdr_dealloc_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched allocation/deallocation.
        /// </summary>
        internal static string pdr_dealloc_mismatch {
            get {
                return ResourceManager.GetString("pdr_dealloc_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory leak.
        /// </summary>
        internal static string pdr_leaked {
            get {
                return ResourceManager.GetString("pdr_leaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangling lock.
        /// </summary>
        internal static string pdr_lock_dangling {
            get {
                return ResourceManager.GetString("pdr_lock_dangling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent lock use.
        /// </summary>
        internal static string pdr_lock_inconsistent {
            get {
                return ResourceManager.GetString("pdr_lock_inconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninitialized lock.
        /// </summary>
        internal static string pdr_lock_uninit {
            get {
                return ResourceManager.GetString("pdr_lock_uninit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential privacy infringement.
        /// </summary>
        internal static string pdr_mem_ctsa {
            get {
                return ResourceManager.GetString("pdr_mem_ctsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid memory access.
        /// </summary>
        internal static string pdr_mem_invalid {
            get {
                return ResourceManager.GetString("pdr_mem_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid partial memory access.
        /// </summary>
        internal static string pdr_mem_invalid_partial {
            get {
                return ResourceManager.GetString("pdr_mem_invalid_partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Shared.
        /// </summary>
        internal static string pdr_mem_sharable {
            get {
                return ResourceManager.GetString("pdr_mem_sharable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninitialized memory access.
        /// </summary>
        internal static string pdr_mem_uninit {
            get {
                return ResourceManager.GetString("pdr_mem_uninit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninitialized partial memory access.
        /// </summary>
        internal static string pdr_mem_uninit_partial {
            get {
                return ResourceManager.GetString("pdr_mem_uninit_partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect mapping.
        /// </summary>
        internal static string pdr_mmap_bad {
            get {
                return ResourceManager.GetString("pdr_mmap_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect mapping.
        /// </summary>
        internal static string pdr_munmap_allocated {
            get {
                return ResourceManager.GetString("pdr_munmap_allocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect mapping.
        /// </summary>
        internal static string pdr_munmap_notmapped {
            get {
                return ResourceManager.GetString("pdr_munmap_notmapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory watch.
        /// </summary>
        internal static string pdr_observe_use {
            get {
                return ResourceManager.GetString("pdr_observe_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data race.
        /// </summary>
        internal static string pdr_race {
            get {
                return ResourceManager.GetString("pdr_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel site information.
        /// </summary>
        internal static string pdr_site_create {
            get {
                return ResourceManager.GetString("pdr_site_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing end site.
        /// </summary>
        internal static string pdr_site_dangling {
            get {
                return ResourceManager.GetString("pdr_site_dangling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing start site.
        /// </summary>
        internal static string pdr_site_nobegin {
            get {
                return ResourceManager.GetString("pdr_site_nobegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data communication.
        /// </summary>
        internal static string pdr_storage_flow {
            get {
                return ResourceManager.GetString("pdr_storage_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory reuse.
        /// </summary>
        internal static string pdr_storage_reuse {
            get {
                return ResourceManager.GetString("pdr_storage_reuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock hierarchy violation.
        /// </summary>
        internal static string pdr_sync_cycle {
            get {
                return ResourceManager.GetString("pdr_sync_cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock hierarchy violation.
        /// </summary>
        internal static string pdr_sync_cycle_whatif {
            get {
                return ResourceManager.GetString("pdr_sync_cycle_whatif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadlock.
        /// </summary>
        internal static string pdr_sync_deadlock {
            get {
                return ResourceManager.GetString("pdr_sync_deadlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out-of-order lock release.
        /// </summary>
        internal static string pdr_sync_order {
            get {
                return ResourceManager.GetString("pdr_sync_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing end task.
        /// </summary>
        internal static string pdr_task_dangling {
            get {
                return ResourceManager.GetString("pdr_task_dangling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing start task.
        /// </summary>
        internal static string pdr_task_nobegin {
            get {
                return ResourceManager.GetString("pdr_task_nobegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphaned task.
        /// </summary>
        internal static string pdr_task_orphaned {
            get {
                return ResourceManager.GetString("pdr_task_orphaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread information.
        /// </summary>
        internal static string pdr_thr_create {
            get {
                return ResourceManager.GetString("pdr_thr_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread information.
        /// </summary>
        internal static string pdr_thr_create_whatif {
            get {
                return ResourceManager.GetString("pdr_thr_create_whatif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application was forcefully terminated.
        /// </summary>
        internal static string pdr_thr_terminate_deadlock {
            get {
                return ResourceManager.GetString("pdr_thr_terminate_deadlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Memory Leak.
        /// </summary>
        internal static string pdr_x_leaked {
            get {
                return ResourceManager.GetString("pdr_x_leaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Invalid Access.
        /// </summary>
        internal static string pdr_x_mem_invalid {
            get {
                return ResourceManager.GetString("pdr_x_mem_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Data Race.
        /// </summary>
        internal static string pdr_x_race {
            get {
                return ResourceManager.GetString("pdr_x_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Library Race.
        /// </summary>
        internal static string pdr_x_race_lib {
            get {
                return ResourceManager.GetString("pdr_x_race_lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Sync Cycle.
        /// </summary>
        internal static string pdr_x_sync_cycle {
            get {
                return ResourceManager.GetString("pdr_x_sync_cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Sync Dangle.
        /// </summary>
        internal static string pdr_x_sync_dangle {
            get {
                return ResourceManager.GetString("pdr_x_sync_dangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Sync Notify.
        /// </summary>
        internal static string pdr_x_sync_notify {
            get {
                return ResourceManager.GetString("pdr_x_sync_notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Thread CDECL.
        /// </summary>
        internal static string pdr_x_thr_cdecl {
            get {
                return ResourceManager.GetString("pdr_x_thr_cdecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Thread Create.
        /// </summary>
        internal static string pdr_x_thr_create {
            get {
                return ResourceManager.GetString("pdr_x_thr_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Thread Death.
        /// </summary>
        internal static string pdr_x_thr_death {
            get {
                return ResourceManager.GetString("pdr_x_thr_death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Thread Infinite Stall.
        /// </summary>
        internal static string pdr_x_thr_stall_infinite {
            get {
                return ResourceManager.GetString("pdr_x_thr_stall_infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Thread Timed Stall.
        /// </summary>
        internal static string pdr_x_thr_stall_timed {
            get {
                return ResourceManager.GetString("pdr_x_thr_stall_timed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Thread Stdcall.
        /// </summary>
        internal static string pdr_x_thr_stdcall {
            get {
                return ResourceManager.GetString("pdr_x_thr_stdcall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Thread Deadlock Terminate.
        /// </summary>
        internal static string pdr_x_thr_terminate_deadlock {
            get {
                return ResourceManager.GetString("pdr_x_thr_terminate_deadlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Thread Infinite Wait.
        /// </summary>
        internal static string pdr_x_thr_wait_infinite {
            get {
                return ResourceManager.GetString("pdr_x_thr_wait_infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXF - Thread Timed Wait.
        /// </summary>
        internal static string pdr_x_thr_wait_timed {
            get {
                return ResourceManager.GetString("pdr_x_thr_wait_timed", resourceCulture);
            }
        }
    }
}
