//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfix.Addin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cfix.Addin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string AboutCmdCaption {
            get {
                return ResourceManager.GetString("AboutCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit &amp;Test....
        /// </summary>
        internal static string AddUnitTestCmdCaption {
            get {
                return ResourceManager.GetString("AddUnitTestCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta, expired.
        /// </summary>
        internal static string BetaLicenseInvalid {
            get {
                return ResourceManager.GetString("BetaLicenseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string BetaLicenseValid {
            get {
                return ResourceManager.GetString("BetaLicenseValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta, {0} days left.
        /// </summary>
        internal static string BetaLicenseValidWithExp {
            get {
                return ResourceManager.GetString("BetaLicenseValidWithExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for &amp;updates.
        /// </summary>
        internal static string CheckForUpdatesCmdCaption {
            get {
                return ResourceManager.GetString("CheckForUpdatesCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Current Solution).
        /// </summary>
        internal static string CurrentSolution {
            get {
                return ResourceManager.GetString("CurrentSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;un Tests.
        /// </summary>
        internal static string DebugCurrentHierItemCaption {
            get {
                return ResourceManager.GetString("DebugCurrentHierItemCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tests: {0}.
        /// </summary>
        internal static string DefaultInfoText {
            get {
                return ResourceManager.GetString("DefaultInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Documentation.
        /// </summary>
        internal static string DocCmdCaption {
            get {
                return ResourceManager.GetString("DocCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection does not include any test item.
        /// </summary>
        internal static string EmptyRun {
            get {
                return ResourceManager.GetString("EmptyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter License Key....
        /// </summary>
        internal static string EnterLicenseCmdCaption {
            get {
                return ResourceManager.GetString("EnterLicenseCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executable &apos;{0}&apos; could not be launched.
        /// </summary>
        internal static string ExecutableCouldNotBeLaunched {
            get {
                return ResourceManager.GetString("ExecutableCouldNotBeLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executable &apos;{0}&apos; could not be found.
        /// </summary>
        internal static string ExecutableNotFound {
            get {
                return ResourceManager.GetString("ExecutableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test &amp;Explorer Window.
        /// </summary>
        internal static string ExplorerCmdCaption {
            get {
                return ResourceManager.GetString("ExplorerCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Explorer.
        /// </summary>
        internal static string ExplorerWindowCaption {
            get {
                return ResourceManager.GetString("ExplorerWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain current configuration.
        /// </summary>
        internal static string FailedToObtainCurrentConfig {
            get {
                return ResourceManager.GetString("FailedToObtainCurrentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The testrun comprises modules of differing CPU architectures or of differing type (DLL vs. EXE). To debug, please restrict your selection to modules of a single CPU architecture/type..
        /// </summary>
        internal static string IncompatibleModule {
            get {
                return ResourceManager.GetString("IncompatibleModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; does not refer to a valid WinDBG installation folder.
        /// </summary>
        internal static string InvalidWindbgInstallFolder {
            get {
                return ResourceManager.GetString("InvalidWindbgInstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis&amp;ual Assert.
        /// </summary>
        internal static string MainMenuCaption {
            get {
                return ResourceManager.GetString("MainMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Assert.
        /// </summary>
        internal static string MsgBoxCaption {
            get {
                return ResourceManager.GetString("MsgBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Visual Assert (Version {0}) is available. Do you wish to download it?.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of Visual Assert is up to date..
        /// </summary>
        internal static string NoNewVersionAvailable {
            get {
                return ResourceManager.GetString("NoNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Solution loaded.
        /// </summary>
        internal static string NoSlnLoaded {
            get {
                return ResourceManager.GetString("NoSlnLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Project: The module does not define any tests..
        /// </summary>
        internal static string NotATestProjectToolTip {
            get {
                return ResourceManager.GetString("NotATestProjectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tests available..
        /// </summary>
        internal static string NoTestsAvailable {
            get {
                return ResourceManager.GetString("NoTestsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}, {2} host process(es), {0}/{1} test cases completed, {6} succeeded, {4} failed, {5} inconclusive..
        /// </summary>
        internal static string ProgressInfo {
            get {
                return ResourceManager.GetString("ProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} succeeded, {1} failed, {2} inconclusive..
        /// </summary>
        internal static string ProgressInfoFinish {
            get {
                return ResourceManager.GetString("ProgressInfoFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build output not available -- rebuild the project.
        /// </summary>
        internal static string ProjectNotBuiltYet {
            get {
                return ResourceManager.GetString("ProjectNotBuiltYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quick Start Page.
        /// </summary>
        internal static string QuickStartCmdCaption {
            get {
                return ResourceManager.GetString("QuickStartCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Last Ru&amp;n.
        /// </summary>
        internal static string ReDebugRunCmdCaption {
            get {
                return ResourceManager.GetString("ReDebugRunCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;start Last Run Without Debugging.
        /// </summary>
        internal static string ReStartRunCmdCaption {
            get {
                return ResourceManager.GetString("ReStartRunCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run still active.
        /// </summary>
        internal static string RunActive {
            get {
                return ResourceManager.GetString("RunActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test &amp;Run Window.
        /// </summary>
        internal static string RunCmdCaption {
            get {
                return ResourceManager.GetString("RunCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Run.
        /// </summary>
        internal static string RunWindowCaption {
            get {
                return ResourceManager.GetString("RunWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a test library or a folder to explore..
        /// </summary>
        internal static string SelectFileOrFolder {
            get {
                return ResourceManager.GetString("SelectFileOrFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Tests Wit&amp;hout Debugging.
        /// </summary>
        internal static string StartCurrentHierItemCmdCaption {
            get {
                return ResourceManager.GetString("StartCurrentHierItemCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded, partly inconclusive.
        /// </summary>
        internal static string SucceededWithInconclusiveParts {
            get {
                return ResourceManager.GetString("SucceededWithInconclusiveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded, partly skipped.
        /// </summary>
        internal static string SucceededWithSkippedParts {
            get {
                return ResourceManager.GetString("SucceededWithSkippedParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one host process is still running. Would you like to terminate this process?.
        /// </summary>
        internal static string TerminateActiveHosts {
            get {
                return ResourceManager.GetString("TerminateActiveHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test run has not finished yet. Do you wish to terminate it?.
        /// </summary>
        internal static string TerminateActiveRun {
            get {
                return ResourceManager.GetString("TerminateActiveRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation copy, expired.
        /// </summary>
        internal static string TrialLicenseInalid {
            get {
                return ResourceManager.GetString("TrialLicenseInalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation copy, {0} days left.
        /// </summary>
        internal static string TrialLicenseValid {
            get {
                return ResourceManager.GetString("TrialLicenseValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized platform: {0}.
        /// </summary>
        internal static string UnrecognizedPlatform {
            get {
                return ResourceManager.GetString("UnrecognizedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported processor architecture..
        /// </summary>
        internal static string UnsupportedArchitecture {
            get {
                return ResourceManager.GetString("UnsupportedArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of module is not supported..
        /// </summary>
        internal static string UnsupportedModule {
            get {
                return ResourceManager.GetString("UnsupportedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check.
        /// </summary>
        internal static string UpdateCheckCaption {
            get {
                return ResourceManager.GetString("UpdateCheckCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates failed. Would you like to open the home page and check manually for updates now?.
        /// </summary>
        internal static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VC++ directory settings have been updated to include the cfix include and library directories. You may have to restart Visual Studio to have these changes take effect..
        /// </summary>
        internal static string VcDirectoriesUpdated {
            get {
                return ResourceManager.GetString("VcDirectoriesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinDBG installation folder.
        /// </summary>
        internal static string WinDbgInstallFolder {
            get {
                return ResourceManager.GetString("WinDbgInstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinDBG integration not configured yet. In the options dialog, open the &apos;Visual Assert/WinDBG Integration&apos; page and configure WinDBG integration..
        /// </summary>
        internal static string WindbgNotConfigured {
            get {
                return ResourceManager.GetString("WindbgNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installed license is not applicable for this product..
        /// </summary>
        internal static string WrongLicense {
            get {
                return ResourceManager.GetString("WrongLicense", resourceCulture);
            }
        }
    }
}
