//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfix.Addin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cfix.Addin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About cfix studio....
        /// </summary>
        internal static string AboutCmdCaption {
            get {
                return ResourceManager.GetString("AboutCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The testrun comprises modules of differing CPU architectures. To debug, please restrict your selection to modules of a single CPU architecture..
        /// </summary>
        internal static string ArchitectureMismatch {
            get {
                return ResourceManager.GetString("ArchitectureMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection does not include any test item.
        /// </summary>
        internal static string EmptyRun {
            get {
                return ResourceManager.GetString("EmptyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cfix Test Explorer Window.
        /// </summary>
        internal static string ExplorerCmdCaption {
            get {
                return ResourceManager.GetString("ExplorerCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cfix Test Explorer.
        /// </summary>
        internal static string ExplorerWindowCaption {
            get {
                return ResourceManager.GetString("ExplorerWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain current configuration.
        /// </summary>
        internal static string FailedToObtainCurrentConfig {
            get {
                return ResourceManager.GetString("FailedToObtainCurrentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cfix.
        /// </summary>
        internal static string MsgBoxCaption {
            get {
                return ResourceManager.GetString("MsgBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}, {2} host process(es), {0}/{1} test cases completed, {4} failed, {5} inconclusive..
        /// </summary>
        internal static string ProgressInfo {
            get {
                return ResourceManager.GetString("ProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} failed, {2} inconclusive..
        /// </summary>
        internal static string ProgressInfoFinish {
            get {
                return ResourceManager.GetString("ProgressInfoFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run still active.
        /// </summary>
        internal static string RunActive {
            get {
                return ResourceManager.GetString("RunActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cfix Run Window.
        /// </summary>
        internal static string RunCmdCaption {
            get {
                return ResourceManager.GetString("RunCmdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cfix Run.
        /// </summary>
        internal static string RunWindowCaption {
            get {
                return ResourceManager.GetString("RunWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a test library or a folder to explore..
        /// </summary>
        internal static string SelectFileOrFolder {
            get {
                return ResourceManager.GetString("SelectFileOrFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded, partly inconclusive.
        /// </summary>
        internal static string SucceededWithInconclusiveParts {
            get {
                return ResourceManager.GetString("SucceededWithInconclusiveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded, partly skipped.
        /// </summary>
        internal static string SucceededWithSkippedParts {
            get {
                return ResourceManager.GetString("SucceededWithSkippedParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test run has not finished yet. Do you wish to terminate it?.
        /// </summary>
        internal static string TerminateActiveRun {
            get {
                return ResourceManager.GetString("TerminateActiveRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized platform: {0}.
        /// </summary>
        internal static string UnrecognizedPlatform {
            get {
                return ResourceManager.GetString("UnrecognizedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported processor architecture..
        /// </summary>
        internal static string UnsupportedArchitecture {
            get {
                return ResourceManager.GetString("UnsupportedArchitecture", resourceCulture);
            }
        }
    }
}
